### ISSUE TITLE
General script in the target artifact

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#165]
If we got a target artifact with several scripts like: `build.sh` and `deploy.sh` should there be a script that runs them both. So you only have to execute one script?
Please discuss in the comments.

**Comment by JensMueller2709** [comment]
i think it make sense if the plugins return one script-file which is fixed in an architectural decision. E.g. a `deployment.sh`script which every plugin has to return. If you need more script-files you could include the execution in the `deployment.sh`. 
If the core or the user wants to deploy the target-artifact it is sufficient to run `deployment.sh`.
I think this idea is compliant with yours.

**Comment by nfode** [comment]
`deployment.sh` is a good name for a general script. But in my opinion we should use several scripts for different tasks, like `build.sh` for build operations not just a general script. If a user wants to run only the build process but he has only the deploments script he has some extra work.

**Comment by mmunozba** [comment]
I'm in favor of having an additional "one-click" script that runs the other scripts. That way, power users can, like u said e.g. only run the build process while normal users can just run the simple one-click script.

**Comment by nfode** [comment]
@mmunozba tagged you in the PR #194
