### ISSUE TITLE
Rest api: csar upload response

### ISSUE THREAD

**Issue by hnicke** [StuPro-TOSCAna/TOSCAna#477]
When issuing a post/put request on /api/csars/{name},
there is a '200' response (OK) and a '201' response (The upload and parsing of the csar was successful). When uploading a csar, server always responds with 201. What is 200 for? This should be unified.

**Comment by c-mueller** [comment]
201 means "Resource Created" will have to invetigate when we return 200 and
adjust the http code correspondingly.

If we externalize the parsing peocess into a seperate thread we could
return 202 (Accepted) this means that the request was accepted but it might
fail while processing.

Am 02.02.2018 1:30 PM schrieb "Heiko Nickerl" <notifications@github.com>:

Assigned #477 <https://github.com/StuPro-TOSCAna/TOSCAna/issues/477> to
@c-mueller <https://github.com/c-mueller>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/StuPro-TOSCAna/TOSCAna/issues/477#event-1454987312>,
or mute
the thread

**Comment by c-mueller** [comment]
The question also is where did you get this information from? Swagger? I am
asking, because i was not able to remove the error code 200 mapping from
swagger. Even though it will not occur in code.

**Comment by hnicke** [comment]
From swagger, indeed.
